### PR TITLE
Command to dump schema

### PR DESCRIPTION
**Pull request by TamasSzigeti**
Adding a command to dump schema for using with apollo codegen for example.
Sorting queries by name to have consistency and be able to rely on this in CI for example

This issue should be move to this repo
https://github.com/thecodingmachine/graphqlite/issues/352

### CODE REVIEW

**Comment by TamasSzigeti** [comment]
@moufmouf @devmaslov Please review

**Comment by TamasSzigeti** [comment]
@moufmouf @devmaslov Any plans to add github CI for this repo? I could do it in another PR, there are some failures already (unrelated to this pr)…

**Comment by moufmouf** [comment]
We would definitely envoyé hacking this répond migrantes to Gitlab CI! +1 for another PR if you can!

**Comment by moufmouf** [comment]
> We would definitely envoyé hacking this répond migrantes to Gitlab CI! +1 for another PR if you can!

Lol just read my message sent from a phone in a hurry. Damn autocorrect!

I meant:

"We would definitely love having this repo migrated to Gitlab CI! +1 for another PR if you can!"

And so, thanks a lot for #94 .

I read your PR and have no special comment. :+1: for me for merging this.

@TamasSzigeti  If you are ok, we could first merge #94 (when it is ready) and then merge this PR (when CI passes?)

Thanks a lot for this PR, it will prove to be very useful!

**Comment by TamasSzigeti** [comment]
No worries, other than gitlab vs github I wasn't even confused that much (:

Yes I'm fine with finishing the CI first I just want to see it running, as it will surely fail – I've seen some issues with dependencies. Maybe let's merge the yaml as it is after review, allow it to fail in master, and then I create a third PR to fix the failures? I'm not sure if github would ever allow running contributed workflows from fork PRs…?

**Comment by TamasSzigeti** [comment]
Then possible a fourth PR addressing the stan errors that for now I've put into a baseline

**Comment by moufmouf** [comment]
Thanks a lot!

**Pull request merged**
