### PR TITLE
[Error handling] Remove category from exceptions

### PR DESCRIPTION
**Pull request by cvergne**
Apply changes from https://github.com/thecodingmachine/graphqlite/pull/685 to the bundle.

> [!WARNING]
> Do no not merge until merge and release of https://github.com/thecodingmachine/graphqlite/pull/685

> [!NOTE]
> Still having error running test about `DependencyInjection/Configuration.php` not compatible with implemented interface. Not fixed it in this PR (as already done in #208), but should probably split it into a distinct PR.

### CODE REVIEW

**Comment by homersimpsons** [comment]
Hello @cvergne thank you for this contribution! Can you update the code to fix the pipeline?

**Comment by cvergne** [comment]
Hello @homersimpsons
The PR requires [the one from the main library](https://github.com/thecodingmachine/graphqlite/pull/685) to be released to work, which will fix the pipeline ^^'

That's why I left the PR in draft as it's not ready.

**Comment by homersimpsons** [comment]
The upstream pull request has been merged. This one should most likely be merged (but needs an upgrade of graphqlite library)

**Comment by andrew-demb** [comment]
> need an update of library

@homersimpsons this is not so easy https://github.com/thecodingmachine/graphqlite-bundle/pull/203#issuecomment-2484381126

**Comment by andrew-demb** [comment]
Replaced by https://github.com/thecodingmachine/graphqlite-bundle/pull/229

Thank you @cvergne

**Pull request closed without merging**
