### PR TITLE
Fix working with session

### PR DESCRIPTION
**Pull request by andrew-demb**
There is no more `SessionInterface` DI alias in Symfony 6

@mistraloz there are fixes for fully Symfony 6 compatibility (with green tests)

### CODE REVIEW

**Comment by swangee** [comment]
@mistraloz Can you help us make this bundle work with Symfony 6, it looks like we have to make a little effort to make the work done.

**Comment by andrew-demb** [comment]
Saw running CI with fails - it is related to bump minimal PHP version.

Added commit with dropping from CI unsupported PHP versions

**Comment by mistraloz** [comment]
Thx @andrew-demb :)

**Comment by andrew-demb** [comment]
@mistraloz thank you too.

Do you plan to tag and release a new version of bundle soon?

**Pull request merged**
