### PR TITLE
symfony 6 (requires SF 5.3+)

### PR DESCRIPTION
**Pull request by janatjak**

### CODE REVIEW

**Comment by mistraloz** [comment]
Thanks for your PR but some tests failed. I'm not sure of why but if you need, you can remove some support (php7.2 and 7.3) and can remove too (if required or better) support for symfony 5.3 (just keep ^5.4 | ^6). If you change the CI, please try to add one for php 8.1.
This PR will be merged on a new `5.4.x` tag.

**Comment by n-ramdi** [comment]
Hello and thanks for your PR,
Any up for this ?

**Comment by faizanakram99** [comment]
@janatjak Thanks for the PR. Are you still working on this ?

**Review by faizanakram99 — APPROVED** [review]

**Comment by swangee** [comment]
Hello, any updates? We would like to update Symfony, but waiting for this PR to be merged.

**Comment by janatjak** [comment]
ping @faizanakram99

please rerun pipelines, thanks 🙏

**Comment by andrew-demb** [comment]
@devmaslov @moufmouf @nguyenk @npeguin could you help to proceed this PR, please?

**Review by faizanakram99 — APPROVED** [review]

**Comment by faizanakram99** [comment]
> ping @faizanakram99
> 
> please rerun pipelines, thanks 🙏

Oh, I'm not a maintainer, just a concerned developer like you

**Pull request merged**
