### PR TITLE
GitHub workflow and dependabot

### PR DESCRIPTION
**Pull request by TamasSzigeti**
* dependabot config
* phpstan config with baseline
* GitHub CI to run phpstan and phpunit on each php version, with both min and max dep versions

### CODE REVIEW

**Comment by TamasSzigeti** [comment]
@moufmouf @devmaslov Could you enable running workflows from forks, please?

https://github.com/organizations/thecodingmachine/settings/actions
image

**Comment by moufmouf** [comment]
> @moufmouf @devmaslov Could you enable running workflows from forks, please?

Done!

**Comment by TamasSzigeti** [comment]
@moufmouf Thanks, but it's still not triggered, maybe it would only pick up the yaml when it lands in master. Idea?

**Comment by moufmouf** [comment]
Indeed! The YAML needs to be on master to enable Github Actions. Let's merge this and see how it goes :D

**Comment by moufmouf** [comment]
Ok, we have the first batch of errors and Github Actions is enabled: https://github.com/thecodingmachine/graphqlite-bundle/actions/runs/956607478

**Pull request merged**
